format = 2

[[dependency]]
name = "8Beat"
github = "razterizer/8Beat"
package = "8Beat"
variant = "applaudio"
version = "1.0.3+build.5"
target = "any"
url = "https://github.com/razterizer/8Beat/releases/download/release-1.0.3.5/8Beat-1.0.3+build.5-applaudio-ho.cbox"
sha256 = "346b182fc46a7c4d247c25312e130be5161ab3b676ff1350f48faf5f146a5663"

[[dependency]]
name = "Termin8or"
github = "razterizer/Termin8or"
package = "Termin8or"
version = "3.0.3+build.9"
target = "any"
url = "https://github.com/razterizer/Termin8or/releases/download/release-3.0.3.9/Termin8or-3.0.3+build.9-ho.cbox"
sha256 = "96db28b2275e173ed0aff714f5c605dfdcede934fa3a324b71f6ee250e3c8ef3"
