format = 2

[[dependency]]
name = "8Beat"
github = "razterizer/8Beat"
package = "8Beat"
variant = "applaudio"
version = "1.0.1+build.3"
target = "any"
url = "https://github.com/razterizer/8Beat/releases/download/release-1.0.1.3/8Beat-1.0.1+build.3-applaudio-ho.cbox"
sha256 = "44ba336a83c83b03707a1ba8208ab2286b556e44876c3e716aadb0d586482605"

[[dependency]]
name = "Termin8or"
github = "razterizer/Termin8or"
package = "Termin8or"
version = "3.0.3+build.9"
target = "any"
url = "https://github.com/razterizer/Termin8or/releases/download/release-3.0.3.9/Termin8or-3.0.3+build.9-ho.cbox"
sha256 = "96db28b2275e173ed0aff714f5c605dfdcede934fa3a324b71f6ee250e3c8ef3"
