name: build ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-program:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          mkdir lib
          cd lib
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git
          git clone https://github.com/razterizer/8Beat.git
          git clone https://github.com/razterizer/AudioLibSwitcher_OpenAL.git --recurse-submodules
          git clone https://github.com/razterizer/TrainOfThought.git

      # Step 3: Install OpenAL
      - name: Install OpenAL
        run: sudo apt install libopenal-dev
      
      # Step 4: Change to the correct directory and build
      - name: Build project
        run: |
          cd Pilot_Episode
          ./build.sh
        continue-on-error: false # Ensure errors are not bypassed
  
      # Run program
      - name: Run program
        if: false
        run: |
             cd Pilot_Episode
             ./bin/pilot_episode

  build-program-with-locked-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          ./Pilot_Episode/fetch-dependencies.py Pilot_Episode/dependencies -y

      # Step 3: Install OpenAL
      - name: Install OpenAL
        run: sudo apt install libopenal-dev
      
      # Step 4: Change to the correct directory and build
      - name: Build project
        run: |
          cd Pilot_Episode
          ./build.sh
        continue-on-error: false # Ensure errors are not bypassed

