name: build ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-program:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          mkdir lib
          cd lib
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git
          git clone https://github.com/razterizer/8Beat.git
          git clone https://github.com/razterizer/AudioLibSwitcher_OpenAL.git --recurse-submodules
          git clone https://github.com/razterizer/TrainOfThought.git

      # Step 3: Install OpenAL
      - name: Install OpenAL
        run: sudo apt install libopenal-dev
      
      # Step 4: Change to the correct directory and build
      - name: Build project
        run: |
          cd Pilot_Episode
          ./build.sh
        continue-on-error: false # Ensure errors are not bypassed
  
      # Step 5: Run program
      - name: Run program
        if: false
        run: |
             cd Pilot_Episode
             ./bin/pilot_episode
             
      # Step 6: Upload executable for valgrind.
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: program-binary
          path: Pilot_Episode/bin

  build-program-with-locked-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          ./Pilot_Episode/fetch-dependencies.py Pilot_Episode/dependencies -y

      # Step 3: Install OpenAL
      - name: Install OpenAL
        run: sudo apt install libopenal-dev
      
      # Step 4: Change to the correct directory and build
      - name: Build project
        run: |
          cd Pilot_Episode
          ./build.sh
        continue-on-error: false # Ensure errors are not bypassed

  valgrind-check:
    runs-on: ubuntu-latest
    needs: build-program

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
        
      - name: Install OpenAL
        run: sudo apt install libopenal-dev

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: program-binary
          path: Pilot_Episode/bin

      - name: Run Valgrind
        run: |
          export ALSOFT_DRIVERS=null  # disables real audio output
          cd Pilot_Episode
          # rm rec.txt # remove if any checked in.
          cp rec_valgrind.txt rec.txt
          chmod +x bin/pilot_episode
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./bin/pilot_episode --log_mode replay --suppress_tty_input --suppress_tty_output --disable_audio

  generate-loc-badge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Install cloc
      - name: Install cloc
        run: sudo apt-get install -y cloc
      
      # Step 3: Count C++ LOC and generate badge as SVG
      - name: Count C++ LOC and generate badge
        run: |
          mkdir -p badges
          CLOC_RESULT=$(cloc --include-ext=cpp,h --json . | jq '.SUM.code')
          echo "$CLOC_RESULT"

          if [ "$CLOC_RESULT" -lt 10000 ]; then
            HUMAN_READABLE=$(printf "%'d" "$CLOC_RESULT" | sed 's/,/ /g')
          else
            HUMAN_READABLE=$(awk "BEGIN { printf \"%.1f k\", $CLOC_RESULT / 1000 }")
          fi

          LABEL="C++ lines"
          LABEL_LEN=${#LABEL}
          VALUE_LEN=${#HUMAN_READABLE}

          # Text length in 1/10 px units (shields.io uses 90-110 per char as base)
          LABEL_TEXTLEN=$((LABEL_LEN * 70))
          VALUE_TEXTLEN=$((VALUE_LEN * 70))

          # Box widths in normal px (scale 0.1 used later)
          LABEL_WIDTH=$((LABEL_TEXTLEN / 10 + 10))
          VALUE_WIDTH=$((VALUE_TEXTLEN / 10 + 10))
          TOTAL_WIDTH=$((LABEL_WIDTH + VALUE_WIDTH))

          # Positions for centered text
          LABEL_CENTER=$((LABEL_WIDTH * 10 / 2))
          VALUE_CENTER=$((LABEL_WIDTH * 10 + VALUE_WIDTH * 10 / 2))

          # Create SVG
          cat <<EOF > badges/loc-badge.svg
          <svg xmlns="http://www.w3.org/2000/svg" width="$TOTAL_WIDTH" height="20" role="img" aria-label="$LABEL: $HUMAN_READABLE">
            <title>$LABEL: $HUMAN_READABLE</title>
            <linearGradient id="s" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <clipPath id="r">
              <rect width="$TOTAL_WIDTH" height="20" rx="3" fill="#fff"/>
            </clipPath>
            <g clip-path="url(#r)">
              <rect width="$LABEL_WIDTH" height="20" fill="#555"/>
              <rect x="$LABEL_WIDTH" width="$VALUE_WIDTH" height="20" fill="#007ec6"/>
              <rect width="$TOTAL_WIDTH" height="20" fill="url(#s)"/>
            </g>
            <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
              <text aria-hidden="true" x="$LABEL_CENTER" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="$LABEL_TEXTLEN">$LABEL</text>
              <text x="$LABEL_CENTER" y="140" transform="scale(.1)" fill="#fff" textLength="$LABEL_TEXTLEN">$LABEL</text>
              <text aria-hidden="true" x="$VALUE_CENTER" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="$VALUE_TEXTLEN">$HUMAN_READABLE</text>
              <text x="$VALUE_CENTER" y="140" transform="scale(.1)" fill="#fff" textLength="$VALUE_TEXTLEN">$HUMAN_READABLE</text>
            </g>
          </svg>
          EOF

      # Step 4: Commit and push the badge to the "badges" branch
      - name: Commit and push badge to badges branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch the latest badges branch
          git fetch origin badges || true
          git checkout badges || git checkout --orphan badges

          # Merge remote changes if the branch already exists
          git pull origin badges --rebase || true

          # Copy badge to the branch and commit
          cp -r badges/* .
          git add loc-badge.svg
          git commit -m "Update LOC badge" || echo "No changes to commit"

          # Push the updated branch
          git push origin badges --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
